apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: mosaic-square-blockchain
  newName: 108199670400.dkr.ecr.ap-northeast-2.amazonaws.com/prod-mosaic-square-blockchain
  newTag: v1.1.0-prod
commonLabels:
  stage: prod
resources:
- ../../base
