spring:
  profiles:
    default: local
  jackson:
    default-property-inclusion: non_null
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat

server:
  port: 80
  ssl:
    enabled: false
