spring:
  config:
    activate:
      on-profile: prod

web3j:
  protocol: https
  client-address:
    https: https://eth-goerli.g.alchemy.com/v2/Wy1sELEyr0eOyS7-TI9qTfI0VcMckXD5
    wss: wss://eth-goerli.g.alchemy.com/v2/Wy1sELEyr0eOyS7-TI9qTfI0VcMckXD5
  contract-address:
    nft: '0x0F0EB638147a8917423D8E4cB08fa7704a1Dfd60'
    admin: '0x2e18062E5611f636270B601bf707da38F1816F3F'
    factory: '0xeCCFA92eAE75c8381625a7b71C421b61b2BA8257'
    primary-market: '0x8d806eCbDd84B6f6177cd2a390F3416bF867b622'
    secondary-market: '0x481d48a7765cCaE47d0185A83a1779eD5DE6B1c7'
  start-block:
    number: 7270064
    force: false
  credentials:
    private-key: '0x8d22a0aa9c43da157ebc24bc7d70c26d198381e042ab93434757752e3f0ee8e5'
cloud:
  aws:
    region: ap-northeast-2
    sqs:
      end-point: https://sqs.ap-northeast-2.amazonaws.com/108199670400
      eth:
        admin: prod-mos-eth-admin.fifo
        factory: prod-mos-eth-factory.fifo
        nft: prod-mos-eth-nft.fifo
        primary-market: prod-mos-eth-primary-market.fifo
        secondary-market: prod-mos-eth-secondary-market.fifo
    credentials:
      access-key-id: AKIARSMJT6KAIKVJPVM6
      secret-access-key: 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

logging:
  level:
    org.springframework: INFO
    com.mosaicsquare: DEBUG
    kotlin.reflect: DEBUG
  config: classpath:log4j2-dev.yml
