apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: mosaic-square-blockchain
  newName: 108199670400.dkr.ecr.ap-northeast-2.amazonaws.com/dev-mosaic-square-blockchain
  newTag: v0.1.2-dev
commonLabels:
  stage: dev
resources:
- ../../base
